[versions]
ktor = "3.0.3"
logback = "1.2.11"
datetime = "0.6.1"
serialization = "1.5.1"
kmath = "1.6.0"
okio = "3.10.0"

[libraries]
ktor-network-tls = { group = "io.ktor", name = "ktor-network-tls", version.ref = "ktor" }
ktor-server-core = { group = "io.ktor", name = "ktor-network-tls", version.ref = "ktor" }
ktor-server-cio = { group = "io.ktor", name = "ktor-network-tls", version.ref = "ktor" }

[bundles]
ktor = ["ktor-network-tls", "ktor-server-core", "ktor-server-cio"]